name: DEV Worker API CI && CD

on:
  push:
    branches:
      - 'DEV'

jobs:

  db-worker-migration:
    runs-on: ubuntu-latest
    name: API Database migration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Change this to your desired .NET version

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef --version 6.0.8

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Backend/NootsWEB/Noots.API.Workers/Noots.API.Workers.csproj

      # Run EF Core migrations
      - name: Run migrations
        run: dotnet ef database update -c ApplicationDatabaseContext -p Backend/NootsWEB/Noots.API.Workers -s Backend/NootsWEB/Noots.API.Workers
        env:
          DatabaseConnection: ${{ secrets.DEV_NOOTS_WORKER_DB_CONNECTION }} # Store your connection string as a secret in your repository settings

  # define the job to build and publish the docker image
  build-and-push-docker-image:
    needs: [db-worker-migration]
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nootsstorm/noots-worker-api
          tags: type=raw,value={{branch}}-{{sha}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./pipeline-files/worker/noots-worker-api.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

            # define the job to build and publish the docker image
  deploy-to-aca:
    needs: [build-and-push-docker-image]
    name: Deploy Worker API to Azure container apps
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in the job
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nootsstorm/noots-worker-api
          tags: type=raw,value={{branch}}-{{sha}}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ steps.meta.outputs.tags }}
          containerAppName: worker-api
          resourceGroup: Noots-DEV
          containerAppEnvironment: managedEnvironment-NootsDEV-bd5e